#!/usr/bin/env python3
# =============================================================================
# core/independent_backtester.py — GEN-26 Independent Execution Engine B
# Decoupled Institutional Backtest Engine evaluating raw model predictions
# under strict real-world execution rules:
#   - Entry at Open T+1 (Strictly eliminating close-to-close lookahead)
#   - Real round-trip friction: 0.90% fees + 0.10% slippage (Total 1.00%)
#   - Daily Price Limits (+/-20% EGX circuit breaker band rejection)
#   - Maximum liquidity participation (<= 10% of 20-day ADV)
#   - Trading suspensions & point-in-time tradability enforcement
# =============================================================================

import os
import sys
import math
import json
import sqlite3
import datetime
from typing import Dict, List, Any, Optional, Tuple
import pandas as pd
import numpy as np

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if WORKSPACE not in sys.path:
    sys.path.insert(0, WORKSPACE)

from core.historical_universe_manager import HistoricalUniverseManager
from core.ranking_engine import CrossSectionalRankingEngine
from core.mcdr_tax_engine import McdrTaxEngine

DATA_DIR = os.path.join(WORKSPACE, "data")
DB_PATH = os.path.join(DATA_DIR, "gen26_production.db")


class IndependentBacktester:
    """
    Engine B: Fully independent, external validation backtester.
    Evaluates predictions generated by any model engine without shared state:
      - Simulates execution strictly on Open T+1.
      - Enforces variable Bid/Ask spread penalty (0.2% mega-caps, 1.5%-2.5% mid/small-caps).
      - Checks 10% 20-day ADV volume participation limits.
      - Deducts brokerage, MCDR clearing, and 10% Egyptian Capital Gains Tax (CGT).
    """

    DEFAULT_COMMISSION_PCT = 0.45       # 0.45% per side = 0.90% round trip
    DEFAULT_SLIPPAGE_PCT = 0.10         # 0.10% baseline execution slippage per trade
    DEFAULT_MAX_ADV_PARTICIPATION = 0.10 # Max 10% of 20-day ADV
    DEFAULT_HOLDING_DAYS = 10           # 10 trading sessions
    EGX_LIMIT_BAND_PCT = 0.20           # +/-20% daily price limit (circuit breaker rejection)

    MEGA_CAP_TICKERS = {
        "COMI.CA", "COMI", "ESRS.CA", "ESRS", "TMGH.CA", "TMGH", "SWDY.CA", "SWDY",
        "ABUK.CA", "ABUK", "ETEL.CA", "ETEL", "MFPC.CA", "MFPC", "EKHO.CA", "EKHO",
        "FWRY.CA", "FWRY", "ORAS.CA", "ORAS", "HRHO.CA", "HRHO", "CERA.CA", "CERA",
        "MASR.CA", "MASR", "EFIH.CA", "EFIH"
    }

    @classmethod
    def get_variable_spread_penalty_pct(cls, ticker: str) -> float:
        """
        Determines Bid/Ask spread penalty based on capitalization and liquidity:
        - 0.20% for Mega-Cap / EGX30 index leaders.
        - 2.00% (range 1.5% - 2.5%) for Mid-Cap and Small-Cap equities.
        """
        sym = ticker.upper().strip()
        if sym in cls.MEGA_CAP_TICKERS:
            return 0.20
        return 2.00

    def __init__(
        self,
        initial_capital_egp: float = 1_000_000.0,
        commission_pct: float = DEFAULT_COMMISSION_PCT,
        slippage_pct: float = DEFAULT_SLIPPAGE_PCT,
        holding_days: int = DEFAULT_HOLDING_DAYS,
        max_positions: int = 5
    ):
        self.initial_capital = initial_capital_egp
        self.commission_pct = commission_pct
        self.slippage_pct = slippage_pct
        self.holding_days = holding_days
        self.max_positions = max_positions

    def load_historical_bars_for_ticker(self, ticker: str) -> pd.DataFrame:
        """Loads and prepares daily OHLCV bars for a specific ticker."""
        if not os.path.exists(DB_PATH):
            return pd.DataFrame()

        conn = sqlite3.connect(DB_PATH)
        query = (
            "SELECT market_date, open_price, high_price, low_price, close_price, volume "
            "FROM historical_daily_bars WHERE ticker = ? ORDER BY market_date ASC"
        )
        df = pd.read_sql_query(query, conn, params=[ticker])
        conn.close()

        if not df.empty:
            df["market_date"] = pd.to_datetime(df["market_date"])
            df.sort_values(by="market_date", inplace=True)
            df.reset_index(drop=True, inplace=True)
        return df

    def run_backtest_on_signals(
        self,
        signals: List[Dict[str, Any]],
        start_date: Optional[str] = None,
        end_date: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Executes independent backtest simulation on an input list of candidate buy signals.
        Each signal must contain:
          - ticker: Equity symbol (e.g. 'COMI.CA')
          - signal_date: Date the prediction was generated (Session T)
          - stop_loss_pct: Optional stop loss percentage (e.g. -5.0)
          - take_profit_pct: Optional target take profit (e.g. +10.0)
          - score: Model alpha/confidence score for ranking
        """
        if not signals:
            return {"status": "EMPTY_SIGNALS", "message": "No signals provided for backtest."}

        # Filter by date range if provided
        sig_df = pd.DataFrame(signals)
        if "signal_date" in sig_df.columns and start_date:
            sig_df = sig_df[sig_df["signal_date"] >= start_date]
        if "signal_date" in sig_df.columns and end_date:
            sig_df = sig_df[sig_df["signal_date"] <= end_date]

        # Group signals by session date to simulate cross-sectional daily selection
        trades_executed = []
        trades_rejected = []
        total_friction_cost_egp = 0.0

        # Cache of price series by ticker to optimize performance
        price_cache: Dict[str, pd.DataFrame] = {}

        for sig in sig_df.to_dict(orient="records"):
            sym = sig.get("ticker", "").upper().strip()
            sig_date_str = str(sig.get("signal_date", ""))[:10]
            if not sym or not sig_date_str:
                continue

            # Load bars
            if sym not in price_cache:
                price_cache[sym] = self.load_historical_bars_for_ticker(sym)
            df_bars = price_cache[sym]

            if df_bars.empty or len(df_bars) < 20:
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "reason": "INSUFFICIENT_HISTORICAL_BARS"
                })
                continue

            # Find row index of Session T (Signal Date)
            sig_dt = pd.to_datetime(sig_date_str)
            sub = df_bars[df_bars["market_date"] == sig_dt]
            if sub.empty:
                # Find nearest previous session
                prev_sub = df_bars[df_bars["market_date"] <= sig_dt]
                if prev_sub.empty:
                    continue
                t_idx = prev_sub.index[-1]
            else:
                t_idx = sub.index[0]

            # Session T+1 index (Next session Open for realistic Entry)
            t_next_idx = t_idx + 1
            if t_next_idx >= len(df_bars):
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "reason": "NO_T_PLUS_1_BAR_AVAILABLE"
                })
                continue

            # Point-in-Time Tradability & Delisting Gate
            t1_date_str = df_bars.iloc[t_next_idx]["market_date"].strftime("%Y-%m-%d")
            if not HistoricalUniverseManager.is_tradable_on(sym, t1_date_str):
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "entry_date": t1_date_str,
                    "reason": "NOT_TRADABLE_ON_T_PLUS_1 (Delisted or Suspended)",
                    "category": "DELISTED_OR_SUSPENDED"
                })
                continue

            # Data Quality Gate (Reject if DQS < 70.0, Reduce size by 50% if 70 <= DQS < 85)
            from core.data_quality import DataQualityEngine
            dqs_info = DataQualityEngine.get_stock_dqs(sym)
            dqs_score = float(dqs_info.get("dqs", 95.0))
            if dqs_score < 70.0:
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "entry_date": t1_date_str,
                    "reason": f"DATA_QUALITY_UNUSABLE (DQS: {dqs_score:.1f} < 70.0)",
                    "category": "DQS_UNUSABLE"
                })
                continue

            # Position sizing multiplier based on DQS
            dqs_sizing_mult = 0.50 if dqs_score < 85.0 else 1.0

            # Session T+1 Price and Limits Check
            bar_t = df_bars.iloc[t_idx]
            bar_t1 = df_bars.iloc[t_next_idx]

            raw_open_t1 = float(bar_t1["open_price"])
            prev_close = float(bar_t["close_price"])

            # Circuit breaker check: Cannot buy if Open T+1 is locked limit up (+19.5% or more)
            cb = CrossSectionalRankingEngine.check_egx_circuit_breaker_band(raw_open_t1, prev_close)
            if not cb["can_buy"]:
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "entry_date": t1_date_str,
                    "reason": "LOCKED_LIMIT_UP_ON_OPEN (+19.5% Circuit Breaker Rejection)",
                    "category": "LIMIT_UP"
                })
                continue

            # 20-day ADV Participation Check (Max 10% of ADV)
            adv_start_idx = max(0, t_next_idx - 20)
            adv_bars = df_bars.iloc[adv_start_idx:t_next_idx]
            adv_20 = float(adv_bars["volume"].mean()) if not adv_bars.empty else float(bar_t["volume"])

            target_pos_capital = (self.initial_capital / self.max_positions) * dqs_sizing_mult
            order_shares = float(sig.get("shares") or (target_pos_capital / max(raw_open_t1, 0.01)))
            if adv_20 > 0 and order_shares > (adv_20 * self.DEFAULT_MAX_ADV_PARTICIPATION):
                trades_rejected.append({
                    "ticker": sym,
                    "signal_date": sig_date_str,
                    "entry_date": t1_date_str,
                    "reason": f"VOLUME_PARTICIPATION_EXCEEDED_10PCT_ADV (Order: {int(order_shares)} > 10% ADV: {int(adv_20 * 0.10)})",
                    "category": "ADV_LIQUIDITY_LIMIT"
                })
                continue

            # Variable Bid/Ask Spread Penalty (0.2% mega-caps, 2.0% mid/small-caps)
            spread_pct = self.get_variable_spread_penalty_pct(sym)
            half_spread_pct = spread_pct / 2.0

            # Apply entry slippage + spread penalty + MCDR regulatory fee
            entry_friction_pct = self.slippage_pct + half_spread_pct
            entry_slip_factor = 1.0 + (entry_friction_pct / 100.0)
            executed_entry_price = round(raw_open_t1 * entry_slip_factor, 2)

            mcdr_reg_rate = McdrTaxEngine.MCDR_CLEARING_FEE_RATE + McdrTaxEngine.FRA_FEE_RATE
            entry_commission = round(executed_entry_price * ((self.commission_pct / 100.0) + mcdr_reg_rate), 4)

            # Holding period simulation (T+1 to T+1+holding_days)
            strat_type = sig.get("strategy_type", "STRATEGY_TREND_BREAKOUT")
            max_holding_days = int(sig.get("holding_days") or self.holding_days)
            exit_idx = min(len(df_bars) - 1, t_next_idx + max_holding_days)
            holding_bars = df_bars.iloc[t_next_idx : exit_idx + 1]

            stop_pct = sig.get("stop_loss_pct", -5.0)
            target_pct = sig.get("take_profit_pct", 10.0)

            # Initial Stop Price:
            if "stop_loss_price" in sig and sig["stop_loss_price"] and float(sig["stop_loss_price"]) > 0:
                curr_stop_price = float(sig["stop_loss_price"])
            else:
                curr_stop_price = executed_entry_price * (1.0 + stop_pct / 100.0)

            target_price = executed_entry_price * (1.0 + target_pct / 100.0) if target_pct else None

            # Dynamic Trailing & Break-even tracking
            peak_price = executed_entry_price
            is_be_locked = False
            is_trailing_active = False

            # Check intraday exits
            realized_exit_price = None
            exit_reason = "HOLDING_HORIZON_EXPIRED"
            actual_exit_date = holding_bars.iloc[-1]["market_date"].strftime("%Y-%m-%d")

            for h_idx in range(len(holding_bars)):
                h_bar = holding_bars.iloc[h_idx]
                h_low = float(h_bar["low_price"])
                h_high = float(h_bar["high_price"])
                h_open = float(h_bar["open_price"])

                # Stop loss trigger (checked against active stop entering this bar)
                if h_low <= curr_stop_price:
                    realized_exit_price = min(h_open, curr_stop_price)
                    actual_exit_date = h_bar["market_date"].strftime("%Y-%m-%d")
                    if is_trailing_active:
                        exit_reason = "TRAILING_STOP_HIT"
                    elif is_be_locked:
                        exit_reason = "BREAKEVEN_STOP_HIT"
                    else:
                        exit_reason = "STOP_LOSS_HIT"
                    break

                # Take profit trigger
                if target_price is not None and h_high >= target_price:
                    realized_exit_price = max(h_open, target_price)
                    actual_exit_date = h_bar["market_date"].strftime("%Y-%m-%d")
                    exit_reason = "TAKE_PROFIT_HIT"
                    break

                # Dynamic trailing and break-even update for subsequent bars:
                if h_high > peak_price:
                    peak_price = h_high

                floating_gain_pct = ((peak_price - executed_entry_price) / executed_entry_price) * 100.0

                # Compute ATR_14 dynamically at current bar
                cur_bar_idx = t_next_idx + h_idx
                atr_slice = df_bars.iloc[max(0, cur_bar_idx - 14) : cur_bar_idx + 1]
                if len(atr_slice) > 1:
                    tr_vals = np.maximum(
                        atr_slice["high_price"].values[1:] - atr_slice["low_price"].values[1:],
                        np.abs(atr_slice["high_price"].values[1:] - atr_slice["close_price"].values[:-1])
                    )
                    atr_14 = float(np.mean(tr_vals))
                else:
                    atr_14 = float(executed_entry_price * 0.02)

                # Rule 1: Break-even Lock at +4.0% floating gain -> Stop raised to Entry + 0.50%
                if floating_gain_pct >= 4.0:
                    be_stop = executed_entry_price * 1.005
                    if be_stop > curr_stop_price:
                        curr_stop_price = be_stop
                        is_be_locked = True

                # Rule 2: Dynamic Trailing Stop at +8.0% floating gain -> Peak - (1.5 * ATR14)
                if floating_gain_pct >= 8.0:
                    trail_stop = peak_price - (1.5 * atr_14)
                    if trail_stop > curr_stop_price:
                        curr_stop_price = trail_stop
                        is_trailing_active = True

            if realized_exit_price is None:
                # Horizon expired: exit at Close of final bar
                realized_exit_price = float(holding_bars.iloc[-1]["close_price"])

            # Apply exit slippage, spread penalty, and exit regulatory fee
            exit_friction_pct = self.slippage_pct + half_spread_pct
            exit_slip_factor = 1.0 - (exit_friction_pct / 100.0)
            executed_exit_price = round(realized_exit_price * exit_slip_factor, 2)
            exit_commission = round(executed_exit_price * ((self.commission_pct / 100.0) + mcdr_reg_rate), 4)

            # Net PnL and 10% Capital Gains Tax (CGT via McdrTaxEngine)
            gross_return_pct = ((realized_exit_price - raw_open_t1) / raw_open_t1) * 100.0
            total_friction_pct = entry_friction_pct + exit_friction_pct + (self.commission_pct * 2) + (mcdr_reg_rate * 200.0)

            net_return_pct = round(((executed_exit_price - executed_entry_price - entry_commission - exit_commission) / executed_entry_price) * 100.0, 2)
            cgt_tax_pct = round(max(0.0, net_return_pct) * McdrTaxEngine.EGYPTIAN_CGT_RATE, 2)
            net_return_after_cgt_pct = round(net_return_pct - cgt_tax_pct, 2)

            trades_executed.append({
                "ticker": sym,
                "strategy_type": strat_type,
                "signal_date": sig_date_str,
                "entry_date": t1_date_str,
                "exit_date": actual_exit_date,
                "entry_price_raw": raw_open_t1,
                "entry_price_executed": executed_entry_price,
                "exit_price_executed": executed_exit_price,
                "peak_price": round(peak_price, 2),
                "spread_penalty_pct": spread_pct,
                "exit_reason": exit_reason,
                "gross_return_pct": round(gross_return_pct, 2),
                "net_return_pct": net_return_pct,
                "cgt_tax_pct": cgt_tax_pct,
                "net_return_after_cgt_pct": net_return_after_cgt_pct,
                "friction_cost_pct": round(total_friction_pct, 2),
                "is_win": net_return_pct > 0
            })

        # Summary Performance Metrics
        n_trades = len(trades_executed)
        if n_trades == 0:
            return {
                "status": "NO_TRADES_EXECUTED",
                "rejected_count": len(trades_rejected),
                "rejections": trades_rejected[:10]
            }

        returns = [t["net_return_pct"] for t in trades_executed]
        returns_after_cgt = [t["net_return_after_cgt_pct"] for t in trades_executed]
        wins = [r for r in returns if r > 0]
        losses = [r for r in returns if r <= 0]

        win_rate_pct = round((len(wins) / n_trades) * 100.0, 2)
        gross_profit = sum(wins) if wins else 0.0
        gross_loss = abs(sum(losses)) if losses else 0.001
        profit_factor = round(gross_profit / gross_loss, 3)

        # Payoff Ratio (Avg Win / Avg Loss)
        avg_win = float(np.mean(wins)) if wins else 0.0
        avg_loss = float(abs(np.mean(losses))) if losses else 0.001
        payoff_ratio = round(avg_win / avg_loss, 2) if avg_loss > 0 else 0.0

        mean_return = np.mean(returns)
        mean_return_after_cgt = np.mean(returns_after_cgt)
        std_return = np.std(returns) if len(returns) > 1 else 1.0
        sharpe = round(float((mean_return / (std_return if std_return > 0 else 1.0)) * math.sqrt(25.2)), 2)

        # Max Drawdown
        cum_ret = np.cumsum(returns)
        running_max = np.maximum.accumulate(cum_ret)
        drawdowns = cum_ret - running_max
        max_drawdown = round(float(np.min(drawdowns)), 2) if len(drawdowns) > 0 else 0.0

        # Strategy Breakdown & Exit Reasons Breakdown
        strat_breakdown = {}
        df_exec = pd.DataFrame(trades_executed)
        if "strategy_type" in df_exec.columns:
            for s_name, s_grp in df_exec.groupby("strategy_type"):
                s_wins = s_grp[s_grp["is_win"]]["net_return_pct"]
                s_losses = s_grp[~s_grp["is_win"]]["net_return_pct"]
                s_win_rate = round((len(s_wins) / len(s_grp)) * 100.0, 2)
                s_pf = round(s_wins.sum() / abs(s_losses.sum()), 3) if abs(s_losses.sum()) > 0 else 999.0
                s_payoff = round(float(s_wins.mean() / abs(s_losses.mean())), 2) if (len(s_wins) > 0 and len(s_losses) > 0) else 0.0
                strat_breakdown[s_name] = {
                    "trades_count": len(s_grp),
                    "win_rate_pct": s_win_rate,
                    "profit_factor": s_pf,
                    "payoff_ratio": s_payoff,
                    "mean_net_return_pct": round(float(s_grp["net_return_pct"].mean()), 2),
                    "mean_net_return_after_cgt_pct": round(float(s_grp["net_return_after_cgt_pct"].mean()), 2)
                }

        exit_reasons_count = dict(df_exec["exit_reason"].value_counts())

        # Rejections categorization
        rejection_breakdown = {
            "limit_up_locked_count": sum(1 for r in trades_rejected if r.get("category") == "LIMIT_UP"),
            "adv_liquidity_exceeded_count": sum(1 for r in trades_rejected if r.get("category") == "ADV_LIQUIDITY_LIMIT"),
            "dqs_unusable_data_count": sum(1 for r in trades_rejected if r.get("category") == "DQS_UNUSABLE"),
            "delisted_or_suspended_count": sum(1 for r in trades_rejected if r.get("category") == "DELISTED_OR_SUSPENDED"),
            "other_count": sum(1 for r in trades_rejected if not r.get("category")),
            "total_rejected": len(trades_rejected)
        }

        # Fiscal CGT liability calculation
        cgt_trades_mock = [{"realized_pnl_egp": t["net_return_pct"] * 1000.0} for t in trades_executed]
        cgt_fiscal = McdrTaxEngine.compute_fiscal_year_cgt(cgt_trades_mock)

        return {
            "status": "BACKTEST_COMPLETED_SUCCESS",
            "engine": "GEN-26 Engine B (Independent Open-T+1 Reality Engine)",
            "execution_rules": {
                "entry_price": "Open T+1 (Strictly verified)",
                "commission_round_trip_pct": self.commission_pct * 2,
                "slippage_round_trip_pct": self.slippage_pct * 2,
                "bid_ask_spread_penalty": "Variable: 0.20% Mega-Caps / 2.00% Mid-Small Caps",
                "max_adv_participation": "Strict 10% of 20-Day ADV",
                "tax_regime": "10% Egyptian Capital Gains Tax (MCDR CGT)",
                "circuit_breaker_limit_band": "+/- 20% EGX Limit Checked",
                "survivorship_filter": "Point-in-Time Tradability Enforced",
                "data_quality_gate": "DQS >= 70.0 Enforced (50% size if 70-85)",
                "breakeven_lock": "Raise stop to Entry + 0.50% at +4.0% floating gain",
                "dynamic_trailing_stop": "Trailing stop = Peak - 1.5 * ATR14 at +8.0% floating gain"
            },
            "total_trades_analyzed": len(signals),
            "trades_executed": n_trades,
            "trades_rejected": len(trades_rejected),
            "rejection_breakdown": rejection_breakdown,
            "win_rate_pct": win_rate_pct,
            "profit_factor": profit_factor,
            "payoff_ratio": payoff_ratio,
            "mean_net_return_pct": round(float(mean_return), 2),
            "mean_net_return_after_cgt_pct": round(float(mean_return_after_cgt), 2),
            "calendar_sharpe": sharpe,
            "max_drawdown_pct": max_drawdown,
            "cgt_fiscal_summary": cgt_fiscal,
            "total_net_cumulative_return_pct": round(float(sum(returns)), 2),
            "strategy_breakdown": strat_breakdown,
            "exit_reasons_breakdown": exit_reasons_count,
            "trades_sample": trades_executed[:5],
            "rejections_sample": trades_rejected[:5]
        }
