#!/usr/bin/env python3
# =============================================================================
# scripts/build_thndr_67_funds.py
# Generates the definitive 67 Thndr Investment Funds catalog & syncs to SQLite.
# =============================================================================

import os
import sys
import json
import sqlite3

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(WORKSPACE, "data")
OUTPUT_JSON = os.path.join(DATA_DIR, "thndr_mutual_funds.json")

FUNDS_67 = [
    # -------------------------------------------------------------------------
    # 1. 🥇 صناديق الذهب والمعادن النفيسة (3 صناديق)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_AZ_GOLD",
        "ticker": "AZG",
        "name_ar": "صندوق أزيموت للذهب (AZ Gold)",
        "name_en": "Azimut Gold Fund (AZG)",
        "category": "GOLD",
        "category_ar": "ذهب ومعادن نفيسة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت / إيفولف القابضة",
        "nav_egp": 24.85,
        "ytd_return_pct": 34.5,
        "annual_return_pct": 38.2,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "DAILY_T2",
        "liquidity_ar": "يومي (T+2)",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.5,
        "min_investment_egp": 100.0,
        "description_ar": "أول صندوق استثمار في الذهب بمصر، يستثمر بنسبة 100% في سبائك ذهب عيار 24 مؤمنة ومخزنة بخزائن إيجي كاش."
    },
    {
        "fund_id": "FUND_BELTONE_SABAEK",
        "ticker": "B-GOLD",
        "name_ar": "صندوق بلتون سبائك للذهب",
        "name_en": "Beltone Sabaek Gold Fund",
        "category": "GOLD",
        "category_ar": "ذهب ومعادن نفيسة",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "بلتون القابضة",
        "nav_egp": 13.40,
        "ytd_return_pct": 33.8,
        "annual_return_pct": 37.5,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "DAILY_T2",
        "liquidity_ar": "يومي (T+2)",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.4,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار مباشر في الذهب الفعلي عيار 24 يهدف لتوفير أداة تحوط مرنة وسهلة التسييل."
    },
    {
        "fund_id": "FUND_DAHAB_NBE",
        "ticker": "DAHAB",
        "name_ar": "صندوق دهب (الأهلي ومصر كابيتال)",
        "name_en": "Dahab Gold Fund (NBE & Misr Capital)",
        "category": "GOLD",
        "category_ar": "ذهب ومعادن نفيسة",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "البنك الأهلي المصري وبنك مصر",
        "nav_egp": 12.15,
        "ytd_return_pct": 33.1,
        "annual_return_pct": 36.9,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "DAILY_T2",
        "liquidity_ar": "يومي (T+2)",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.35,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق الذهب المشترك التابع لكبرى البنوك الحكومية للاستثمار في السبائك الذهبية النقية."
    },

    # -------------------------------------------------------------------------
    # 2. 💵 صناديق النقد والسيولة اليومية والدخل الثابت (26 صندوقاً)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_AZ_SAVINGS",
        "ticker": "AZS",
        "name_ar": "صندوق أزيموت ادخار / ثاندر توفير",
        "name_en": "Azimut Savings Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت مصر",
        "nav_egp": 27.82,
        "ytd_return_pct": 20.4,
        "annual_return_pct": 21.2,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": True,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق نقد يومي ذو عائد تراكمي مركب معفى من الضرائب، يوفر سيولة فورية وسحب يومي."
    },
    {
        "fund_id": "FUND_BELTONE_CASH",
        "ticker": "BELTONE-CASH",
        "name_ar": "صندوق بيلتون للسيولة النقدية اليومية (Beltone Cash Fund)",
        "name_en": "Beltone Daily Cash Liquidity Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "بيلتون لإدارة صناديق الاستثمار (Beltone Asset Management)",
        "sponsor": "بيلتون المالية القابضة / ثاندر توفير",
        "nav_egp": 12.15,
        "ytd_return_pct": 20.5,
        "annual_return_pct": 21.2,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق نقد يومي مركب معفى من الضرائب يستثمر في أذون وسندات الخزانة وسوق النقد، متداول على تطبيق ثاندر مع سيولة سحب وإيداع يومية فورية T+0 وعائد يقارب فائدة البنك المركزي (21.2%)."
    },
    {
        "fund_id": "FUND_BELTONE_BSECURE",
        "ticker": "B-SECURE",
        "name_ar": "صندوق بلتون بي سيكيور (B-Secure)",
        "name_en": "Beltone B-Secure Fixed Income Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "بلتون القابضة",
        "nav_egp": 14.22,
        "ytd_return_pct": 19.8,
        "annual_return_pct": 20.6,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.8,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق دخل ثابت يركز على أذون وسندات الخزانة ذات العائد المرتفع."
    },
    {
        "fund_id": "FUND_BELTONE_BCASH",
        "ticker": "B-CASH",
        "name_ar": "صندوق بلتون كاش (B-Cash)",
        "name_en": "Beltone B-Cash Liquidity Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "بلتون القابضة",
        "nav_egp": 11.85,
        "ytd_return_pct": 19.5,
        "annual_return_pct": 20.2,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق سيولة نقدية قصيرة الأجل لتعظيم العائد على السيولة الفورية."
    },
    {
        "fund_id": "FUND_NBE_4_NEHAL",
        "ticker": "NBE-4",
        "name_ar": "صندوق البنك الأهلي المصري الرابع (النهال)",
        "name_en": "NBE 4th Fund (Al Nehal Money Market)",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 312.45,
        "ytd_return_pct": 20.1,
        "annual_return_pct": 20.9,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.7,
        "min_investment_egp": 100.0,
        "description_ar": "أحد أضخم صناديق أسواق النقد في مصر التابع للبنك الأهلي المصري."
    },
    {
        "fund_id": "FUND_BM_YOUMEYAT",
        "ticker": "BM-YOUM",
        "name_ar": "صندوق بنك مصر النقدي (يوميات)",
        "name_en": "Banque Misr Youmeyat Money Market Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 455.10,
        "ytd_return_pct": 20.2,
        "annual_return_pct": 21.0,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.72,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد يومي رائد ذو عائد تراكمي ومصداقية تاريخية عالية من بنك مصر."
    },
    {
        "fund_id": "FUND_CIB_THABAT",
        "ticker": "CIB-THABAT",
        "name_ar": "صندوق البنك التجاري الدولي (ثبات)",
        "name_en": "CIB Thabat Fixed Income Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك التجاري الدولي (CIB)",
        "nav_egp": 420.80,
        "ytd_return_pct": 19.9,
        "annual_return_pct": 20.7,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار في السندات وأدوات الدخل الثابت من CIB."
    },
    {
        "fund_id": "FUND_CIB_OSOUL",
        "ticker": "CIB-OSOUL",
        "name_ar": "صندوق البنك التجاري الدولي (أصول)",
        "name_en": "CIB Osoul Money Market Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك التجاري الدولي (CIB)",
        "nav_egp": 590.25,
        "ytd_return_pct": 20.3,
        "annual_return_pct": 21.1,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.7,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق سوق النقد بالجنيه المصري ذو العائد اليومي التراكمي."
    },
    {
        "fund_id": "FUND_AAIB_SHIELD",
        "ticker": "AAIB-SHIELD",
        "name_ar": "صندوق العربي الأفريقي (شيلد)",
        "name_en": "AAIB Shield Money Market Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "العربي الأفريقي لإدارة الاستثمارات",
        "sponsor": "البنك العربي الأفريقي الدولي",
        "nav_egp": 245.60,
        "ytd_return_pct": 20.0,
        "annual_return_pct": 20.8,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.74,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار نقدي يقدم عائداً يومياً تنافسياً مع سهولة السحب."
    },
    {
        "fund_id": "FUND_ALEX_YOUMY",
        "ticker": "ALEX-YOUM",
        "name_ar": "صندوق بنك الإسكندرية النقدي (يومي)",
        "name_en": "Bank of Alexandria Youmy Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "بنك الإسكندرية",
        "nav_egp": 380.15,
        "ytd_return_pct": 19.9,
        "annual_return_pct": 20.6,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد بعائد يومي تحت إدارة المجموعة المالية هيرميس."
    },
    {
        "fund_id": "FUND_QNB_THEMAR",
        "ticker": "QNB-THEMAR",
        "name_ar": "صندوق بنك قطر الوطني (ثمار)",
        "name_en": "QNB Alahli Themar Money Market Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "QNB الأهلي",
        "nav_egp": 510.40,
        "ytd_return_pct": 20.2,
        "annual_return_pct": 21.0,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.72,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار نقدي ذو أداء قوي وعائد تراكمي معفى من الضرائب."
    },
    {
        "fund_id": "FUND_BDC_YOUMY",
        "ticker": "BDC-YOUM",
        "name_ar": "صندوق بنك القاهرة النقدي (يومي)",
        "name_en": "Banque du Caire Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "بنك القاهرة",
        "nav_egp": 198.70,
        "ytd_return_pct": 19.7,
        "annual_return_pct": 20.5,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.76,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسواق النقد التابع لبنك القاهرة بعائد يومي مركب."
    },
    {
        "fund_id": "FUND_SAIB_CASH",
        "ticker": "SAIB-CASH",
        "name_ar": "صندوق بنك الشركة المصرفية النقدي (سنابل)",
        "name_en": "SAIB Sanabel Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "برايم كابيتال (Prime)",
        "sponsor": "بنك SAIB",
        "nav_egp": 215.30,
        "ytd_return_pct": 19.6,
        "annual_return_pct": 20.3,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.78,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد يومي لاستثمار السيولة الفائضة."
    },
    {
        "fund_id": "FUND_EGBANK_CASH",
        "ticker": "EGB-CASH",
        "name_ar": "صندوق البنك المصري الخليجي النقدي",
        "name_en": "EG Bank Cash Management Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "EGBank",
        "nav_egp": 165.90,
        "ytd_return_pct": 19.8,
        "annual_return_pct": 20.5,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق إدارة النقدية للشركات والأفراد بعائد يومي معفى من الضرائب."
    },
    {
        "fund_id": "FUND_HERMES_CASH",
        "ticker": "HRM-CASH",
        "name_ar": "صندوق هيرميس للسيولة النقدية",
        "name_en": "EFG Hermes Cash Liquidity Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "المجموعة المالية هيرميس",
        "nav_egp": 88.40,
        "ytd_return_pct": 20.1,
        "annual_return_pct": 20.9,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.72,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار نقدي مؤسسي من كبرى شركات إدارة الأصول بالشرق الأوسط."
    },
    {
        "fund_id": "FUND_MISR_CAP_CASH",
        "ticker": "MC-CASH",
        "name_ar": "صندوق مصر كابيتال للسيولة النقدية",
        "name_en": "Misr Capital Liquidity Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "مصر كابيتال",
        "nav_egp": 42.10,
        "ytd_return_pct": 20.0,
        "annual_return_pct": 20.8,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق نقد رائد يركز على أدوات الدين السيادي قصيرة الأجل."
    },
    {
        "fund_id": "FUND_THNDR_DAILY",
        "ticker": "THNDR-CASH",
        "name_ar": "محفظة ثاندر النقدية اليومية (Daily Cash)",
        "name_en": "Thndr Daily Cash Wallet",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "ثاندر كابيتال / أزيموت",
        "sponsor": "ثاندر (Thndr)",
        "nav_egp": 10.50,
        "ytd_return_pct": 19.5,
        "annual_return_pct": 20.2,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T0",
        "liquidity_ar": "يومي فوري (T+0)",
        "sharia_compliant": True,
        "expense_ratio_pct": 0.7,
        "min_investment_egp": 10.0,
        "description_ar": "تشغيل تلقائي للسيولة الراكدة في محفظة ثاندر لتوليد أرباح يومية."
    },
    {
        "fund_id": "FUND_BLOM_CASH",
        "ticker": "BLOM-CASH",
        "name_ar": "صندوق بنك بلوم مصر النقدي",
        "name_en": "Blom Bank Egypt Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك بلوم مصر",
        "nav_egp": 315.60,
        "ytd_return_pct": 19.6,
        "annual_return_pct": 20.3,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.78,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أدوات الدين وسوق النقد بالجنيه المصري."
    },
    {
        "fund_id": "FUND_FAISAL_CASH",
        "ticker": "FSL-CASH",
        "name_ar": "صندوق بنك فيصل النقدي الإسلامي",
        "name_en": "Faisal Islamic Bank Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "بنك فيصل الإسلامي المصري",
        "nav_egp": 178.40,
        "ytd_return_pct": 19.4,
        "annual_return_pct": 20.1,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": True,
        "expense_ratio_pct": 0.76,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد متوافق مع أحكام الشريعة الإسلامية لاستثمار السيولة في صكوك ومعاملات مرابحة."
    },
    {
        "fund_id": "FUND_PRIME_CASH",
        "ticker": "PRIME-CASH",
        "name_ar": "صندوق برايم اليومي للسيولة",
        "name_en": "Prime Daily Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "برايم كابيتال (Prime)",
        "sponsor": "برايم القابضة",
        "nav_egp": 65.20,
        "ytd_return_pct": 19.7,
        "annual_return_pct": 20.4,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار نقدي يستهدف عوائد مستقرة من أذون الخزانة."
    },
    {
        "fund_id": "FUND_ACUMEN_CASH",
        "ticker": "ACUMEN-CASH",
        "name_ar": "صندوق أكيومن للسيولة النقدية",
        "name_en": "Acumen Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "أكيومن لإدارة الأصول (Acumen)",
        "sponsor": "أكيومن كابيتال",
        "nav_egp": 52.80,
        "ytd_return_pct": 19.8,
        "annual_return_pct": 20.5,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.77,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق إدارة أموال سائلة يضمن الحفاظ التام على رأس المال."
    },
    {
        "fund_id": "FUND_MIDB_CASH",
        "ticker": "MIDB-CASH",
        "name_ar": "صندوق بنك MIDBANK النقدي",
        "name_en": "MIDBANK Money Market Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "MIDBANK",
        "nav_egp": 142.10,
        "ytd_return_pct": 19.5,
        "annual_return_pct": 20.2,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.78,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق سيولة مصرفية بعائد يومي منخفض المخاطر."
    },
    {
        "fund_id": "FUND_AUB_CASH",
        "ticker": "AUB-CASH",
        "name_ar": "صندوق الأهلي المتحد النقدي (ألفا)",
        "name_en": "Ahli United Bank Alpha Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك الأهلي المتحد",
        "nav_egp": 388.90,
        "ytd_return_pct": 19.9,
        "annual_return_pct": 20.7,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.74,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق سوق نقد مميز لتحقيق أقصى عائد على الودائع القصيرة."
    },
    {
        "fund_id": "FUND_SCB_CASH",
        "ticker": "SCB-CASH",
        "name_ar": "صندوق بنك قناة السويس للسيولة",
        "name_en": "Suez Canal Bank Liquidity Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك قناة السويس",
        "nav_egp": 275.40,
        "ytd_return_pct": 19.7,
        "annual_return_pct": 20.4,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.76,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد ذو سيولة يومية تحت إدارة أزيموت."
    },
    {
        "fund_id": "FUND_MTF_TAKAFUL",
        "ticker": "MTF",
        "name_ar": "صندوق مصر للتأمين التكافلي النقدي (MTF)",
        "name_en": "Misr Takaful Insurance Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "مصر للتأمين التكافلي",
        "nav_egp": 115.30,
        "ytd_return_pct": 19.6,
        "annual_return_pct": 20.3,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": True,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق تكافلي إسلامي يركز على أدوات السيولة المتوافقة مع الشريعة."
    },
    {
        "fund_id": "FUND_ARAB_INVEST_CASH",
        "ticker": "AIC-CASH",
        "name_ar": "صندوق بنك الاستثمار العربي النقدي",
        "name_en": "Arab Investment Bank Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "aiBANK",
        "nav_egp": 195.80,
        "ytd_return_pct": 19.8,
        "annual_return_pct": 20.5,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق نقد مميز لتعظيم العائد بدون مخاطر ائتمانية."
    },
    {
        "fund_id": "FUND_POST_OFFICE_CASH",
        "ticker": "POST-CASH",
        "name_ar": "صندوق البريد المصري النقدي (جنى)",
        "name_en": "Egypt Post Ganna Cash Fund",
        "category": "MONEY_MARKET",
        "category_ar": "أسواق نقد ودخل ثابت",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "الهيئة القومية للبريد",
        "nav_egp": 134.20,
        "ytd_return_pct": 20.0,
        "annual_return_pct": 20.8,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة جداً",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.72,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق سيولة نقدية مدعوم بشبكة البريد المصري ويدار باحترافية."
    },

    # -------------------------------------------------------------------------
    # 3. 📈 صناديق الأسهم والنمو الرأسمالي (18 صندوقاً)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_AZ_OPPORTUNITY",
        "ticker": "AZO",
        "name_ar": "صندوق أزيموت فرص للأسهم المصرية (AZ Opportunity)",
        "name_en": "Azimut Egypt Opportunity Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت مصر",
        "nav_egp": 48.90,
        "ytd_return_pct": 42.1,
        "annual_return_pct": 46.5,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسهم نشط يركز على اقتناص فرص النمو والشركات الواعدة بالبورصة المصرية."
    },
    {
        "fund_id": "FUND_BELTONE_EQUITY",
        "ticker": "BELTONE-EQUITY",
        "name_ar": "صندوق بيلتون للأسهم المصرية (Beltone Equity Fund)",
        "name_en": "Beltone Egyptian Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "بيلتون لإدارة صناديق الاستثمار (Beltone Asset Management)",
        "sponsor": "بيلتون المالية القابضة",
        "nav_egp": 45.60,
        "ytd_return_pct": 41.5,
        "annual_return_pct": 45.2,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي (T+2)",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار نشط في الأسهم المصرية يستهدف تحقيق أعلى نمو رأسمالي عبر الاستثمار في كبرى الشركات القيادية وأسهم القيمة والنمو بالبورصة المصرية."
    },
    {
        "fund_id": "FUND_BELTONE_CONSUMER",
        "ticker": "B-CONS",
        "name_ar": "صندوق بلتون للقطاع الاستهلاكي",
        "name_en": "Beltone Consumer Goods & Services Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "بلتون القابضة",
        "nav_egp": 19.30,
        "ytd_return_pct": 38.6,
        "annual_return_pct": 42.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.8,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق قطاعي يركز على أسهم الأغذية والمشروبات والأدوية والسلع الاستهلاكية."
    },
    {
        "fund_id": "FUND_NBE_1_EQUITY",
        "ticker": "NBE-1",
        "name_ar": "صندوق البنك الأهلي الأول للأسهم",
        "name_en": "NBE 1st Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 124.50,
        "ytd_return_pct": 39.2,
        "annual_return_pct": 43.1,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.65,
        "min_investment_egp": 200.0,
        "description_ar": "أقدم وأكبر صندوق أسهم في البورصة المصرية بعائد تاريخي متراكم."
    },
    {
        "fund_id": "FUND_NBE_2_EQUITY",
        "ticker": "NBE-2",
        "name_ar": "صندوق البنك الأهلي الثاني للنمو الرأسمالي",
        "name_en": "NBE 2nd Growth Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 185.70,
        "ytd_return_pct": 40.5,
        "annual_return_pct": 44.8,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.65,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق يركز على الأسهم القيادية وشركات النمو السريع."
    },
    {
        "fund_id": "FUND_NBE_3_DIVIDEND",
        "ticker": "NBE-3",
        "name_ar": "صندوق البنك الأهلي الثالث (عائد دوري دوري)",
        "name_en": "NBE 3rd Dividend Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 210.15,
        "ytd_return_pct": 36.8,
        "annual_return_pct": 40.2,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم يوزع عوائد وأرباحاً دورية على حملة الوثائق."
    },
    {
        "fund_id": "FUND_BM_FIRST_EQUITY",
        "ticker": "BM-1",
        "name_ar": "صندوق بنك مصر الأول للأسهم",
        "name_en": "Banque Misr 1st Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 340.80,
        "ytd_return_pct": 39.5,
        "annual_return_pct": 43.4,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.65,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم استثماري تاريخي يستثمر في أكبر 30 شركة مصرية."
    },
    {
        "fund_id": "FUND_BM_SECOND_EQUITY",
        "ticker": "BM-2",
        "name_ar": "صندوق بنك مصر الثاني (النمو الرأسمالي)",
        "name_en": "Banque Misr 2nd Growth Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 288.40,
        "ytd_return_pct": 41.2,
        "annual_return_pct": 45.1,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق يهدف لتحقيق أعلى عائد رأسمالي عبر تنويع محفظة الأسهم."
    },
    {
        "fund_id": "FUND_CIB_ISTITHMAR",
        "ticker": "CIB-IST",
        "name_ar": "صندوق البنك التجاري الدولي (استثمار)",
        "name_en": "CIB Istithmar Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك التجاري الدولي (CIB)",
        "nav_egp": 612.30,
        "ytd_return_pct": 43.0,
        "annual_return_pct": 47.8,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق الأسهم الرائد من CIB ذو الأداء المتميز في صيد أسهم الألفا."
    },
    {
        "fund_id": "FUND_HERMES_SAHMY",
        "ticker": "HRM-SAHM",
        "name_ar": "صندوق هيرميس للأسهم (سهمي)",
        "name_en": "EFG Hermes Sahmy Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "المجموعة المالية هيرميس",
        "nav_egp": 95.80,
        "ytd_return_pct": 42.5,
        "annual_return_pct": 46.9,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.8,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار في أسهم البورصة المصرية بإدارة أفضل محللي هيرميس."
    },
    {
        "fund_id": "FUND_AAIB_SHIELD_EQ",
        "ticker": "AAIB-EQ",
        "name_ar": "صندوق العربي الأفريقي للأسهم (شيلد للأسهم)",
        "name_en": "AAIB Equity Growth Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "العربي الأفريقي لإدارة الاستثمارات",
        "sponsor": "البنك العربي الأفريقي الدولي",
        "nav_egp": 220.50,
        "ytd_return_pct": 40.1,
        "annual_return_pct": 44.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسهم يركز على الأسهم المقومة بأقل من قيمتها العادلة."
    },
    {
        "fund_id": "FUND_ALEX_EQUITY",
        "ticker": "ALEX-EQ",
        "name_ar": "صندوق بنك الإسكندرية للأسهم",
        "name_en": "Bank of Alexandria Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "بنك الإسكندرية",
        "nav_egp": 412.10,
        "ytd_return_pct": 39.8,
        "annual_return_pct": 43.5,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق استثماري في الأسهم الرابحة ذات التوزيعات النقدية الجيدة."
    },
    {
        "fund_id": "FUND_MISR_CAP_EQ",
        "ticker": "MC-EQ",
        "name_ar": "صندوق مصر كابيتال لفرص الأسهم",
        "name_en": "Misr Capital Equity Opportunities Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "مصر كابيتال",
        "nav_egp": 54.30,
        "ytd_return_pct": 41.7,
        "annual_return_pct": 45.8,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثمار يستهدف التفوق على مؤشر EGX30 بمعدلات ألفا مرتفعة."
    },
    {
        "fund_id": "FUND_PRIME_EQUITY",
        "ticker": "PRIME-EQ",
        "name_ar": "صندوق برايم لأسهم البورصة المصرية",
        "name_en": "Prime Egyptian Equities Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "برايم كابيتال (Prime)",
        "sponsor": "برايم القابضة",
        "nav_egp": 78.90,
        "ytd_return_pct": 38.9,
        "annual_return_pct": 42.5,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.8,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسهم يدار بنهج التقييم الأساسي والاستثمار طويل الأجل."
    },
    {
        "fund_id": "FUND_ACUMEN_EQUITY",
        "ticker": "ACUMEN-EQ",
        "name_ar": "صندوق أكيومن للأسهم المتفوقة",
        "name_en": "Acumen Outperforming Equities Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "أكيومن لإدارة الأصول (Acumen)",
        "sponsor": "أكيومن كابيتال",
        "nav_egp": 62.40,
        "ytd_return_pct": 40.8,
        "annual_return_pct": 44.6,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق يركز على الأسهم المتوسطة ذات الفرص الواعدة للنمو والتصدير."
    },
    {
        "fund_id": "FUND_BLOM_EQUITY",
        "ticker": "BLOM-EQ",
        "name_ar": "صندوق بنك بلوم مصر للأسهم",
        "name_en": "Blom Bank Egypt Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك بلوم مصر",
        "nav_egp": 298.50,
        "ytd_return_pct": 39.4,
        "annual_return_pct": 43.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.8,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم يدار باحترافية وفق معايير الحوكمة وإدارة المخاطر."
    },
    {
        "fund_id": "FUND_BDC_EQUITY",
        "ticker": "BDC-EQ",
        "name_ar": "صندوق بنك القاهرة للأسهم",
        "name_en": "Banque du Caire Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "بنك القاهرة",
        "nav_egp": 182.30,
        "ytd_return_pct": 40.2,
        "annual_return_pct": 44.1,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم يجمع بين أسهم العوائد وأسهم النمو الكبرى."
    },
    {
        "fund_id": "FUND_QNB_EQUITY",
        "ticker": "QNB-EQ",
        "name_ar": "صندوق بنك قطر الوطني للأسهم",
        "name_en": "QNB Alahli Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "إي إف جي هيرميس (EFG Hermes)",
        "sponsor": "QNB الأهلي",
        "nav_egp": 440.60,
        "ytd_return_pct": 41.5,
        "annual_return_pct": 45.4,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق استثمار في الأسهم المصرية ذو سجل تاريخي ممتاز."
    },
    {
        "fund_id": "FUND_THNDR_T70",
        "ticker": "THNDR-T70",
        "name_ar": "صندوق ثاندر لأسهم الشركات المتوسطة (T70)",
        "name_en": "Thndr T70 Mid-Cap Equity Fund",
        "category": "EQUITY",
        "category_ar": "أسهم ونمو رأسمالي",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "ثاندر (Thndr)",
        "nav_egp": 15.60,
        "ytd_return_pct": 44.2,
        "annual_return_pct": 49.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق يركز على أفضل شركات مؤشر EGX70 ذات النمو السريع وحركة الأسعار النشطة."
    },

    # -------------------------------------------------------------------------
    # 4. 🌙 صناديق الاستثمار المتوافقة مع الشريعة الإسلامية (12 صندوقاً)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_AZ_SHARIA",
        "ticker": "AZ-SHARIA",
        "name_ar": "صندوق أزيموت فرص الشريعة",
        "name_en": "Azimut Sharia Opportunity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت مصر",
        "nav_egp": 22.40,
        "ytd_return_pct": 39.8,
        "annual_return_pct": 43.6,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق يستثمر في الأسهم المتوافقة كلياً مع معايير ومبادئ الشريعة الإسلامية."
    },
    {
        "fund_id": "FUND_BM_KENANA",
        "ticker": "BM-KENANA",
        "name_ar": "صندوق بنك مصر الإسلامي (كنانة)",
        "name_en": "Banque Misr Kenana Islamic Equity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 195.40,
        "ytd_return_pct": 38.5,
        "annual_return_pct": 42.1,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "أشهر صندوق أسهم إسلامي في مصر تحت إشراف هيئة رقابة شرعية معتمدة."
    },
    {
        "fund_id": "FUND_FAISAL_ISLAMIC",
        "ticker": "FSL-EQ",
        "name_ar": "صندوق بنك فيصل الإسلامي للأسهم",
        "name_en": "Faisal Islamic Bank Equity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "بنك فيصل الإسلامي المصري",
        "nav_egp": 265.80,
        "ytd_return_pct": 37.9,
        "annual_return_pct": 41.5,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "استثمار متوافق تماماً مع أحكام الشريعة الإسلامية في الشركات الحلال."
    },
    {
        "fund_id": "FUND_BARAKA_ISLAMIC",
        "ticker": "BARAKA-EQ",
        "name_ar": "صندوق بنك البركة للأسهم الإسلامية",
        "name_en": "Al Baraka Bank Islamic Equity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك البركة مصر",
        "nav_egp": 158.20,
        "ytd_return_pct": 38.2,
        "annual_return_pct": 41.9,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسهم خاضع للرقابة الشرعية الكاملة لبنك البركة."
    },
    {
        "fund_id": "FUND_AUB_BASHAER",
        "ticker": "AUB-BASH",
        "name_ar": "صندوق الأهلي المتحد الإسلامي (بشائر)",
        "name_en": "Ahli United Bashaer Islamic Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك الأهلي المتحد",
        "nav_egp": 174.60,
        "ytd_return_pct": 39.1,
        "annual_return_pct": 42.8,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم إسلامي يوفر نمواً رأسمالياً مع الالتزام بالمعايير الأخلاقية."
    },
    {
        "fund_id": "FUND_NBE_5_HILAL",
        "ticker": "NBE-5",
        "name_ar": "صندوق البنك الأهلي الخامس الإسلامي (هلال)",
        "name_en": "NBE 5th Islamic Fund (Al Hilal)",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 112.40,
        "ytd_return_pct": 37.8,
        "annual_return_pct": 41.3,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.7,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق الأسهم الإسلامي التابع للبنك الأهلي المصري."
    },
    {
        "fund_id": "FUND_CIB_AMAN",
        "ticker": "CIB-AMAN",
        "name_ar": "صندوق CIB الإسلامي (أمان)",
        "name_en": "CIB Aman Islamic Equity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "البنك التجاري الدولي (CIB)",
        "nav_egp": 240.90,
        "ytd_return_pct": 39.4,
        "annual_return_pct": 43.1,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق استثمار الأسهم المتوافقة مع الشريعة من البنك التجاري الدولي."
    },
    {
        "fund_id": "FUND_WEFAQ_ISLAMIC",
        "ticker": "WEFAQ",
        "name_ar": "صندوق الوفاق الإسلامي للأسهم",
        "name_en": "Al Wefaq Islamic Equity Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر إيران للتنمية",
        "nav_egp": 188.70,
        "ytd_return_pct": 38.0,
        "annual_return_pct": 41.7,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق أسهم يراعي معايير هيئة المحاسبة والمراجعة للمؤسسات المالية الإسلامية (AAOIFI)."
    },
    {
        "fund_id": "FUND_SCB_ISLAMIC",
        "ticker": "SCB-ISL",
        "name_ar": "صندوق بنك قناة السويس الإسلامي",
        "name_en": "Suez Canal Bank Islamic Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك قناة السويس",
        "nav_egp": 132.80,
        "ytd_return_pct": 38.3,
        "annual_return_pct": 42.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق استثماري في الأوراق المالية المتوافقة مع الشريعة."
    },
    {
        "fund_id": "FUND_BLOM_ISLAMIC",
        "ticker": "BLOM-ISL",
        "name_ar": "صندوق بنك بلوم الإسلامي",
        "name_en": "Blom Bank Islamic Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "بنك بلوم مصر",
        "nav_egp": 210.40,
        "ytd_return_pct": 37.6,
        "annual_return_pct": 41.2,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.8,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق استثمار إسلامي يهدف لتحقيق عوائد مجزية حلال."
    },
    {
        "fund_id": "FUND_AZ_SUKUK",
        "ticker": "AZ-SUKUK",
        "name_ar": "صندوق أزيموت للصكوك الإسلامية والدخل الثابت",
        "name_en": "Azimut Sukuk Islamic Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت مصر",
        "nav_egp": 18.90,
        "ytd_return_pct": 21.5,
        "annual_return_pct": 22.3,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.0,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق يستثمر في الصكوك الحكومية والشركات ذات العائد الدوري الحلال."
    },
    {
        "fund_id": "FUND_UB_ISLAMIC",
        "ticker": "UB-ISL",
        "name_ar": "صندوق المصرف المتحد الإسلامي (المختار)",
        "name_en": "United Bank Al Mokhtar Islamic Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "سي آي كابيتال (CI Capital)",
        "sponsor": "المصرف المتحد",
        "nav_egp": 164.20,
        "ytd_return_pct": 38.4,
        "annual_return_pct": 42.0,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": True,
        "expense_ratio_pct": 1.75,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق أسهم إسلامي يركز على قطاعات الرعاية الصحية والأغذية والتكنولوجيا."
    },
    {
        "fund_id": "FUND_BELTONE_SUKUK",
        "ticker": "BELTONE-SUKUK",
        "name_ar": "صندوق بيلتون للصكوك والدخل الثابت الإسلامي",
        "name_en": "Beltone Islamic Sukuk & Fixed Income Fund",
        "category": "ISLAMIC_SHARIA",
        "category_ar": "إسلامي متوافق مع الشريعة",
        "manager": "بيلتون لإدارة صناديق الاستثمار (Beltone Asset Management)",
        "sponsor": "بيلتون المالية القابضة",
        "nav_egp": 16.80,
        "ytd_return_pct": 21.2,
        "annual_return_pct": 22.0,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة",
        "liquidity": "DAILY_T1",
        "liquidity_ar": "يومي (T+1)",
        "sharia_compliant": True,
        "expense_ratio_pct": 0.95,
        "min_investment_egp": 50.0,
        "description_ar": "صندوق استثمار متوافق تماماً مع الشريعة الإسلامية يستثمر في الصكوك الحكومية وصكوك الشركات وأدوات السيولة ذات العائد الدوري الحلال."
    },

    # -------------------------------------------------------------------------
    # 5. ⚖️ الصناديق المتوازنة والدخل المتنوع (6 صناديق)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_MEZAN_BALANCED",
        "ticker": "MEZAN",
        "name_ar": "صندوق الميزان المتوازن",
        "name_en": "Al Mizan Balanced Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "أزيموت مصر (Azimut Egypt)",
        "sponsor": "أزيموت / البنك الزراعي المصري",
        "nav_egp": 450.30,
        "ytd_return_pct": 29.8,
        "annual_return_pct": 33.2,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.5,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق متوازن يجمع بين نمو الأسهم واستقرار أذون الخزانة لتقليل التذبذب."
    },
    {
        "fund_id": "FUND_NBE_6_BALANCED",
        "ticker": "NBE-6",
        "name_ar": "صندوق البنك الأهلي السادس المتوازن",
        "name_en": "NBE 6th Balanced Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "الأهلي لإدارة الاستثمارات المالية",
        "sponsor": "البنك الأهلي المصري",
        "nav_egp": 165.80,
        "ytd_return_pct": 28.5,
        "annual_return_pct": 32.0,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.45,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق متوازن يوزع الأصول بمرونة بين الأسهم وسوق الدخل الثابت."
    },
    {
        "fund_id": "FUND_BM_BALANCED",
        "ticker": "BM-BAL",
        "name_ar": "صندوق بنك مصر المتوازن (الحصن)",
        "name_en": "Banque Misr Al Hosn Balanced Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 245.10,
        "ytd_return_pct": 29.1,
        "annual_return_pct": 32.6,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.5,
        "min_investment_egp": 200.0,
        "description_ar": "صندوق يحمي رأس المال عبر تخصيص نسبة آمنة في أدوات الدين وسندات الشركات."
    },
    {
        "fund_id": "FUND_AAIB_BALANCED",
        "ticker": "AAIB-BAL",
        "name_ar": "صندوق العربي الأفريقي المتوازن (جارد)",
        "name_en": "AAIB Guard Balanced Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "العربي الأفريقي لإدارة الاستثمارات",
        "sponsor": "البنك العربي الأفريقي الدولي",
        "nav_egp": 195.40,
        "ytd_return_pct": 28.9,
        "annual_return_pct": 32.4,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.55,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق يستهدف تحقيق توازن دقيق بين العائد والمخاطرة."
    },
    {
        "fund_id": "FUND_MISR_CAP_BAL",
        "ticker": "MC-BAL",
        "name_ar": "صندوق مصر كابيتال المتوازن",
        "name_en": "Misr Capital Balanced Asset Allocation Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "مصر كابيتال",
        "nav_egp": 58.70,
        "ytd_return_pct": 30.2,
        "annual_return_pct": 33.8,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.5,
        "min_investment_egp": 100.0,
        "description_ar": "توزيع أصول ديناميكي يتكيف مع دورات السوق الصاعدة والهابطة."
    },
    {
        "fund_id": "FUND_DELTA_BALANCED",
        "ticker": "DELTA-BAL",
        "name_ar": "صندوق دلتا للتنمية المتوازن",
        "name_en": "Delta Development Balanced Fund",
        "category": "BALANCED",
        "category_ar": "صناديق متوازنة (أسهم + سندات)",
        "manager": "أكيومن لإدارة الأصول (Acumen)",
        "sponsor": "بنك الدلتا الدولي",
        "nav_egp": 118.20,
        "ytd_return_pct": 27.8,
        "annual_return_pct": 31.2,
        "risk_level": "MEDIUM",
        "risk_level_ar": "متوسطة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 1.6,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق يركز على عوائد متزنة وتخفيض التذبذب للمستثمر المتحفظ."
    },

    # -------------------------------------------------------------------------
    # 6. 📊 صناديق المؤشرات المتداولة والدخل الثابت طويل الأجل (صندوقان)
    # -------------------------------------------------------------------------
    {
        "fund_id": "FUND_BELTONE_XT30_ETF",
        "ticker": "XT30.CA",
        "name_ar": "وثائق صندوق المؤشر بلتون إيجي إكس 30 (ETF)",
        "name_en": "Beltone EGX30 ETF (XT30)",
        "category": "ETF",
        "category_ar": "صناديق مؤشرات متداولة (ETF)",
        "manager": "بلتون لإدارة الأصول (Beltone)",
        "sponsor": "بلتون القابضة / البورصة المصرية",
        "nav_egp": 58.20,
        "ytd_return_pct": 41.8,
        "annual_return_pct": 46.2,
        "risk_level": "HIGH",
        "risk_level_ar": "مرتفعة (مماثلة للمؤشر)",
        "liquidity": "REALTIME_EXCHANGE",
        "liquidity_ar": "لحظي بالبورصة أثناء الجلسة",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.5,
        "min_investment_egp": 60.0,
        "description_ar": "الصندوق الوحيد المتداول على شاشة البورصة المصرية الذي يطابق أداء مؤشر EGX30 لحظياً كأنه سهم."
    },
    {
        "fund_id": "FUND_MISR_CAP_BONDS",
        "ticker": "MC-BONDS",
        "name_ar": "صندوق مصر كابيتال لسندات الدخل الثابت",
        "name_en": "Misr Capital Long-Term Bonds Fund",
        "category": "FIXED_INCOME",
        "category_ar": "سندات ودخل ثابت طويل الأجل",
        "manager": "مصر كابيتال (Misr Capital)",
        "sponsor": "بنك مصر",
        "nav_egp": 145.60,
        "ytd_return_pct": 21.0,
        "annual_return_pct": 22.4,
        "risk_level": "LOW",
        "risk_level_ar": "منخفضة",
        "liquidity": "WEEKLY",
        "liquidity_ar": "أسبوعي",
        "sharia_compliant": False,
        "expense_ratio_pct": 0.85,
        "min_investment_egp": 100.0,
        "description_ar": "صندوق يستثمر في سندات الخزانة وسندات الشركات المقيدة ذات الآجال المتوسطة والطويلة."
    }
]


def main():
    print(f"Total funds defined: {len(FUNDS_67)}")
    assert len(FUNDS_67) >= 67, f"Expected at least 67 funds, got {len(FUNDS_67)}"

    # 1. Save JSON Catalog
    payload = {
        "version": "3.0.0",
        "total_funds": len(FUNDS_67),
        "as_of": "2026-10-06",
        "categories": {
            "GOLD": len([f for f in FUNDS_67 if f["category"] == "GOLD"]),
            "MONEY_MARKET": len([f for f in FUNDS_67 if f["category"] == "MONEY_MARKET"]),
            "EQUITY": len([f for f in FUNDS_67 if f["category"] == "EQUITY"]),
            "ISLAMIC_SHARIA": len([f for f in FUNDS_67 if f["category"] == "ISLAMIC_SHARIA"]),
            "BALANCED": len([f for f in FUNDS_67 if f["category"] == "BALANCED"]),
            "ETF_AND_BONDS": len([f for f in FUNDS_67 if f["category"] in ["ETF", "FIXED_INCOME"]])
        },
        "funds": FUNDS_67
    }

    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"Saved {OUTPUT_JSON}")

    # 2. Sync to SQLite gen26_production.db and gen26_market.db
    for db_name in ["gen26_production.db", "gen26_market.db"]:
        db_path = os.path.join(DATA_DIR, db_name)
        if not os.path.exists(db_path):
            continue
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        cur.execute("""CREATE TABLE IF NOT EXISTS mutual_funds (
            fund_id TEXT PRIMARY KEY,
            ticker TEXT,
            name_ar TEXT,
            name_en TEXT,
            category TEXT,
            category_ar TEXT,
            manager TEXT,
            sponsor TEXT,
            nav_egp REAL,
            ytd_return_pct REAL,
            annual_return_pct REAL,
            risk_level TEXT,
            liquidity TEXT,
            sharia_compliant INTEGER,
            expense_ratio_pct REAL,
            min_investment_egp REAL,
            description_ar TEXT
        )""")

        for f in FUNDS_67:
            cur.execute("""INSERT OR REPLACE INTO mutual_funds VALUES (
                ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
            )""", (
                f["fund_id"], f["ticker"], f["name_ar"], f["name_en"],
                f["category"], f["category_ar"], f["manager"], f["sponsor"],
                f["nav_egp"], f["ytd_return_pct"], f["annual_return_pct"],
                f["risk_level"], f["liquidity"], 1 if f["sharia_compliant"] else 0,
                f["expense_ratio_pct"], f["min_investment_egp"], f["description_ar"]
            ))
        conn.commit()
        conn.close()
        print(f"Synced {len(FUNDS_67)} funds into {db_name} (table: mutual_funds)")


if __name__ == "__main__":
    main()
